[package]
  cjc-version = "1.0.0"
  name = "Diablo"
  description = "Diablo and Hellfire game"
  version = "0.1.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = "--cfg . --disable-reflection --static-std --static-libs -O2 -Woff unused"
  override-compile-option = "--disable-reflection --static-std --static-libs -O2"
  link-option = "-s"
  package-configuration = {}

[dependencies]
  cenum = { path = "dependencies/cenum", output-type = "dynamic" }
  cjsfml = { path = "dependencies/cjsfml", output-type = "static" }
  clibrary = { path = "dependencies/clibrary", output-type = "static" }
  customiterators = { path = "dependencies/customiterators", output-type = "static" }
  dgengine = { path = "dependencies/dgengine", output-type = "static" }
  endian = { path = "dependencies/endian", output-type = "static" }

[replace]
  endian = { path = "dependencies/endian", output-type = "static" }

[ffi.c]
  physfs = { path = "dependencies/physfs" }
  StormLib = { path = "dependencies/StormLib" }

[target.x86_64-unknown-linux-gnu]
  compile-option = "--static"

[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = ["dependencies/stdx/linux_x86_64_llvm/static/stdx"]

[target.x86_64-w64-mingw32.bin-dependencies]
  path-option = ["dependencies/stdx/windows_x86_64_llvm/static/stdx"]
