[package]
  cjc-version = "1.0.0"
  name = "clibrary"
  description = "load C dynamic libraries"
  version = "1.0.1"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
