name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }} with Cangjie ${{ matrix.cangjie_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cangjie_version: 1.0.0
          - os: ubuntu-latest
            cangjie_version: 1.0.1
          - os: windows-latest
            cangjie_version: 1.0.1
          - os: macos-latest
            cangjie_version: 1.0.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OpenGL (Linux)
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: freeglut3-dev
          version: 1.0
          execute_install_scripts: true

      - name: Setup Cangjie
        uses: Zxilly/setup-cangjie@v2.0.0
        with:
          channel: lts
          version: ${{ matrix.cangjie_version }}
          archive-path: ./cangjie-archive

      - name: Build
        run: cjpm build

      - name: Test
        run: cjpm test
