name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OpenGL (Linux)
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: freeglut3-dev
          version: 1.0
          execute_install_scripts: true

      - name: Setup Cangjie
        uses: Zxilly/setup-cangjie@v1.8.0
        with:
          channel: lts
          version: 1.0.0
          tool-cache: true
          archive-path: ./cangjie-archive

      - name: Build
        run: cjpm build

      - name: Test
        run: cjpm test
