[package]
  cjc-version = "1.0.0"
  name = "clibrary_example"
  description = "clibrary example"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  clibrary = { path = "./.." }
